#!/usr/bin/env sh

#
# for this to work you must configure sudo such that
# it will be able to run the command without password
#
# see this wiki page for information:
#  - https://github.com/koekeishiya/yabai/wiki/Installing-yabai-(latest-release)#configure-scripting-addition
#
# yabai -m signal --add event=dock_did_restart action="sudo yabai --load-sa"
# sudo yabai --load-sa
#

# global settings
yabai -m config                                 \
    external_bar                 off:40:0       \
    menubar_opacity              1.0            \
    mouse_follows_focus          off            \
    focus_follows_mouse          off            \
    display_arrangement_order    default        \
    window_origin_display        default        \
    window_placement             second_child   \
    window_zoom_persist          on             \
    window_shadow                on             \
    window_opacity               off            \
    window_opacity_duration      0.0            \
    active_window_opacity        1.0            \
    normal_window_opacity        0.90           \
    window_animation_duration    0.0            \
    window_animation_easing      ease_out_expo  \
    insert_feedback_color        0xff444444     \
    split_ratio                  0.70           \
    split_type                   vertical       \
    mouse_modifier               fn             \
    mouse_action1                move           \
    mouse_action2                resize         \
    mouse_drop_action            stack          \
    layout                       bsp            \
    top_padding                  0              \
    bottom_padding               0              \
    left_padding                 0              \
    right_padding                0              \
    window_gap                   8              \
    auto_balance                 off

yabai -m config --space last split_ratio 0.30

echo "yabai configuration loaded.."

# yabai -m signal --add event=window_created action="if /usr/local/bin/yabai -m query --windows --space | /usr/local/bin/jq '.[].\"split-type\"' | /usr/bin/grep -q vertical; then /usr/local/bin/yabai -m window last --stack \$YABAI_WINDOW_ID; fi"

# yabai -m signal --add event=window_deminimized action="if /usr/local/bin/yabai -m query --windows --space | /usr/local/bin/jq '.[].\"split-type\"' | /usr/bin/grep -q vertical; then /usr/local/bin/yabai -m window last --stack \$YABAI_WINDOW_ID; fi"

# 系统设置 \u7cfb\u7edf\u8bbe\u7f6e
yabai -m rule --add app="^系统设置$" manage=off
# yabai -m rule --add app="微信" manage=off
# yabai -m rule --add app="微信" manage=off
yabai -m rule --add app="微信" title!="微信 \(聊天\)" manage=off
# yabai -m rule --add app="微信" title="微信 \(窗口\)" manage=on
# yabai -m rule --add app="Code" title="^Welcome$" manage=off
yabai -m rule --add app="^计算器$" manage=off
